apiVersion: v1
kind: Service
metadata:
  name: {{ template "dash-chart.fullname" . }}-mysql-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: "6603"
    port: {{ .Values.service.db.port }}
    targetPort: {{ .Values.service.db.targetPort }}
  selector:
    app: {{ template "dash-chart.fullname" . }}-mysql-dash
  type: {{ .Values.service.db.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dash-chart.fullname" . }}-web-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: "8080"
    port: {{ .Values.service.web.port }}
    targetPort:  {{ .Values.service.web.targetPort }}
  selector:
    app: {{ template "dash-chart.fullname" . }}-web-dash
  type: {{ .Values.service.web.type }}